{"uuid":"b2dc98d0-4136-476d-b580-4c24166738a7","name":"org.auntor.testCases.SettingsTest","children":["3d79f35d-1b1b-42ca-8038-0eee97aea393","f4850ea1-532e-4a46-8517-d7b4f575d0a7","b9d33235-60c9-42b8-998b-a5187de3f41a","5d423768-fb6f-448a-ad06-5e5d8f473262","d1c1e4cd-ffc1-4a05-a484-d5b6e41deff8","9fa90c31-a013-4fe2-aff1-76bfb3338d88","2a8d57ed-dc73-4275-9a15-f163ee4e215a","6f214ef4-02a1-444d-8d6e-27b8ace4fc18","0c3241a2-e23f-4964-9ca8-5f231771f33c","17dd4622-f04d-4d13-b5c7-060790b5d1d0","37c23fcf-dcd9-4b3a-b55b-df7080663f11","3ed80ae6-7e74-4092-badd-93c0ea658992"],"befores":[{"name":"automationEnvStart","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'Auntors-MacBook-Air.local', ip: 'fe80:0:0:0:4c4:ccc1:f81f:2c20%en0'","trace":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'Auntors-MacBook-Air.local', ip: 'fe80:0:0:0:4c4:ccc1:f81f:2c20%en0'\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)\n\tat io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:229)\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:92)\n\tat org.auntor.utilities.BaseClass.capabilities(BaseClass.java:83)\n\tat org.auntor.utilities.BaseClass.automationEnvStart(BaseClass.java:28)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)\n\tat org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\n\tat org.testng.TestRunner.run(TestRunner.java:585)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\n\tat org.testng.TestNG.run(TestNG.java:1037)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\nCaused by: org.openqa.selenium.WebDriverException: Connection refused\nBuild info: version: '4.8.1', revision: '8ebccac989'\nSystem info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6.1', java.version: '11.0.18'\nDriver info: driver.version: AppiumDriver\n\tat io.appium.java_client.remote.AppiumCommandExecutor.lambda$execute$4(AppiumCommandExecutor.java:274)\n\tat java.base/java.util.Optional.orElseGet(Optional.java:369)\n\tat io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:273)\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)\n\t... 31 more\nCaused by: java.net.ConnectException: Connection refused\n\tat java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)\n\tat java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)\n\tat io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1680237808492,"stop":1680237809479}],"afters":[{"name":"automationEnvStop","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1680237810891,"stop":1680237810892}],"links":[],"start":1680237808456,"stop":1680237810898}