{"uuid":"f433b013-0d15-4407-9a8f-9820bc2ce48f","name":"org.auntor.testCases.SettingsTest","children":["15b09372-21c3-493b-9b8b-9b6a7f38b9c1","3a3599de-88b6-4aeb-8966-771106db63a8","12ece7a5-6d3b-47a0-9909-7f82672cb8da","422f89ab-d923-430e-a75c-10db816d6d25","9d387121-9080-4a0b-b02c-2e9ef0e71a34","db1f51c8-dc0d-4522-b7b8-cbc0d1c73a0e","0ae4d641-0038-43ba-a2e2-01f7520b2498","5a8603e0-8850-451b-b840-1416d348c5d7","3fd41fd1-b33e-4545-9c74-00a5d18d7eac","154449be-4818-4da2-af78-8456615b1b2f","fda6853e-47e9-44bb-acb3-9da6a792e364","4c1eb3f3-f291-4a13-98ae-18d01220215d"],"befores":[{"name":"automationEnvStart","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'Auntors-MacBook-Air.local', ip: 'fe80:0:0:0:4c4:ccc1:f81f:2c20%en0'","trace":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. \nHost info: host: 'Auntors-MacBook-Air.local', ip: 'fe80:0:0:0:4c4:ccc1:f81f:2c20%en0'\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)\n\tat io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:229)\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:92)\n\tat org.auntor.utilities.BaseClass.capabilities(BaseClass.java:82)\n\tat org.auntor.utilities.BaseClass.automationEnvStart(BaseClass.java:28)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)\n\tat org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\n\tat org.testng.TestRunner.run(TestRunner.java:585)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\n\tat org.testng.TestNG.run(TestNG.java:1037)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\nCaused by: org.openqa.selenium.WebDriverException: Connection refused\nBuild info: version: '4.8.1', revision: '8ebccac989'\nSystem info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6.1', java.version: '11.0.18'\nDriver info: driver.version: AppiumDriver\n\tat io.appium.java_client.remote.AppiumCommandExecutor.lambda$execute$4(AppiumCommandExecutor.java:274)\n\tat java.base/java.util.Optional.orElseGet(Optional.java:369)\n\tat io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:273)\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)\n\t... 31 more\nCaused by: java.net.ConnectException: Connection refused\n\tat java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)\n\tat java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)\n\tat io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1680236732629,"stop":1680236737254}],"afters":[{"name":"automationEnvStop","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1680236738643,"stop":1680236738644}],"links":[],"start":1680236732601,"stop":1680236738648}